# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MDAnalysis
name:             MDAnalysis
tagline:          A Python package for the analysis of molecular dynamics simulations.
description:      A Python package for the analysis of molecular dynamics simulations.
url:              https://www.mdanalysis.org
# leave baseurl empty,
# see https://github.com/MDAnalysis/MDAnalysis.github.io/issues/16#issuecomment-385572553
baseurl:          
author:
  name:           The MDAnalysis Team
  url:            https://twitter.com/mdanalysis
  email:          mdnalysis-devel@googlegroups.com

images:           /public/images
data:             /public/data
js:               /js
blog:             /blog

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

# Blog pagination
paginate_path:   "/blog/page:num/"
paginate:        3

# jekyll-feed
# - our previous feed was called atom.xml so we use it instead
#   of the default feed.xml
feed:
  path: atom.xml

# Custom vars
version:          1.0.0

# see also https://help.github.com/articles/repository-metadata-on-github-pages/
# for what GitHub makes available in site.github
github:
  repo:           https://github.com/MDAnalysis/mdanalysis
  docs:           https://docs.mdanalysis.org/dev
  issues:         https://github.com/MDAnalysis/mdanalysis/issues
  wiki:           https://github.com/MDAnalysis/mdanalysis/wiki
pypi:
  package:        https://pypi.org/project/MDAnalysis
  tests:          https://pypi.org/project/MDAnalysisTests
  docs:           https://docs.mdanalysis.org
mailinglists:
  discussion:
    name:         mdnalysis-discussion
    url:          https://groups.google.com/group/mdnalysis-discussion
  developer: 
    name:         developer
    url:          https://groups.google.com/group/mdnalysis-devel
twitter:
  name:           mdanalysis
  url:            https://twitter.com/mdanalysis
docs:
  mdanalysis:
     name:        Online Documentation
     url:         https://docs.mdanalysis.org
  development:
     name:        Development Version Online Documentation
     url:         https://docs.mdanalysis.org/dev
  userguide:
    name:         User Guide
    url:          https://userguide.mdanalysis.org
  quickstart:
    name:         Quick Start Guide
    url:          https://userguide.mdanalysis.org/stable/quickstart.html

algolia:
  index_name: mdanalysis
  read_only_api_key: 307d780013d06fdde7a4eae462db0e74

numfocus:
  donate:            https://numfocus.org/donate-to-mdanalysis
  sponsored_project: https://numfocus.org/project/mdanalysis
  donate_button:     <a href="https://numfocus.org/donate-to-mdanalysis" target="_blank" style="background:#FF9200;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#000000;display:inline-block;border-radius:3px">Donate Now</a>
  