# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            MDAnalysis
name:             MDAnalysis
tagline:          molecular simulations data analysis
description:      working with data in the molecular sciences
# long_description is not currently used by the theme
long_description: |
                  MDAnalysis is a Python library which enables the handling and
                  analysis of data from computer simulations of many-body
                  systems at the molecular scale, spanning use cases from
                  interactions of drugs with proteins to novel materials. It is
                  widely used in the scientific community and is written by
                  scientists for scientists.
url:              https://www.mdanalysis.org
# leave baseurl empty,
# see https://github.com/MDAnalysis/MDAnalysis.github.io/issues/16#issuecomment-385572553
baseurl:          
author:
  name:           The MDAnalysis Team
  url:            https://twitter.com/mdanalysis
  email:          mdanalysis@numfocus.org

images:           /public/images
js:               /js
blog:             /blog

# see https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed

# Blog pagination
paginate_path:   "/blog/page:num/"
paginate:        3

# jekyll-feed
# - our previous feed was called atom.xml so we use it instead
#   of the default feed.xml
feed:
  path: atom.xml

# Custom vars
version:          2.0.0

# see also https://help.github.com/articles/repository-metadata-on-github-pages/
# for what GitHub makes available in site.github
github:
  repo:           https://github.com/MDAnalysis/mdanalysis
  docs:           https://docs.mdanalysis.org/dev
  issues:         https://github.com/MDAnalysis/mdanalysis/issues
  wiki:           https://github.com/MDAnalysis/mdanalysis/wiki
pypi:
  package:        https://pypi.org/project/MDAnalysis
  tests:          https://pypi.org/project/MDAnalysisTests
  docs:           https://docs.mdanalysis.org
mailinglists:
  discussion:
    name:         mdnalysis-discussion
    url:          https://groups.google.com/group/mdnalysis-discussion
  developer: 
    name:         developer
    url:          https://groups.google.com/group/mdnalysis-devel
  gsoc:
    name:         MDAnalysis GSoC list
    url:          https://groups.google.com/a/mdanalysis.org/g/gsoc
twitter:
  name:           mdanalysis
  url:            https://twitter.com/mdanalysis
discord:
  name:           MDAnalysis
  url:            https://discord.com/channels/807348386012987462/
  invite:         https://discord.gg/fXTSfDJyxE
docs:
  mdanalysis:
     name:        Online Documentation
     url:         https://docs.mdanalysis.org
  development:
     name:        Development Version Online Documentation
     url:         https://docs.mdanalysis.org/dev
  userguide:
    name:         User Guide
    url:          https://userguide.mdanalysis.org
  quickstart:
    name:         Quick Start Guide
    url:          https://userguide.mdanalysis.org/stable/examples/quickstart.html

# The algolia.read_only_api_key may be safely put into frontend code
# and this is not a security issue.
algolia:
  index_name:        mdanalysis
  appId:             Y8HJT3NO22
  read_only_api_key: 68fa6789d0a275a311f68914e0c2366e

numfocus:
  donate:            https://numfocus.org/donate-to-mdanalysis
  sponsored_project: https://numfocus.org/project/mdanalysis
  donate_button:     <a href="https://numfocus.org/donate-to-mdanalysis" target="_blank" style="background:#FF9200;padding:10px;margin:10px 0px;text-align:center;text-decoration:none;font-size:12pt;color:#000000;display:inline-block;border-radius:3px">Donate Now</a>
  
